package com.camexch.browser;

final class VirtualCameraScript {
    static final String SCRIPT =
            "(function(){"
                    + "if(window.__camexchInstalled)return;window.__camexchInstalled=true;"
                    + "function log(m){try{if(window.CamExchLog)window.CamExchLog.log(String(m));}catch(e){}}"
                    + "log('Front Camera 4 hook installed url='+location.href);"
                    + "const originalGet=navigator.mediaDevices&&navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices):null;"
                    + "const originalEnum=navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices?navigator.mediaDevices.enumerateDevices.bind(navigator.mediaDevices):null;"
                    + "function isVirtualRequest(c){"
                    + " if(!c||!c.video)return false;"
                    + " const v=c.video;"
                    + " if(v===true)return true;"
                    + " const fm=v.facingMode;"
                    + " const id=v.deviceId;"
                    + " function hasUser(x){return x==='user'||(x&&x.exact==='user')||(x&&x.ideal==='user')||(Array.isArray(x)&&x.indexOf('user')>=0);}"
                    + " function hasVirtual(x){return x==='camexch-front-camera-4'||(x&&x.exact==='camexch-front-camera-4')||(x&&x.ideal==='camexch-front-camera-4');}"
                    + " if(hasUser(fm)||hasVirtual(id))return true;"
                    + " if(fm==='environment'||(fm&&fm.exact==='environment')||(fm&&fm.ideal==='environment'))return false;"
                    + " return !id&&!fm;"
                    + "}"
                    + "async function photoStream(c){"
                    + " log('using MJPEG photo stream');"
                    + " const canvas=document.createElement('canvas');canvas.width=640;canvas.height=480;"
                    + " const ctx=canvas.getContext('2d');"
                    + " const img=new Image();img.crossOrigin='anonymous';let alive=true;"
                    + " function draw(){try{if(img.naturalWidth){ctx.drawImage(img,0,0,canvas.width,canvas.height);}}catch(e){} if(alive)requestAnimationFrame(draw);}"
                    + " const photo=window.CamExchBridge&&window.CamExchBridge.getPhotoDataUrl();if(!photo||photo.indexOf('ERROR:')===0)throw new Error(photo||'Source bridge unavailable');img.src=photo;draw();"
                    + " const stream=canvas.captureStream(10);"
                    + " stream.getVideoTracks().forEach(t=>{const stop=t.stop.bind(t);t.stop=function(){alive=false;stop();};});"
                    + " await addAudio(stream,c);return stream;"
                    + "}"
                    + "async function addAudio(stream,c){"
                    + " if(c&&c.audio&&originalGet){try{const audio=await originalGet({audio:c.audio,video:false});audio.getAudioTracks().forEach(t=>stream.addTrack(t));}catch(e){}}"
                    + "}"
                    + "function waitIce(pc){return pc.iceGatheringState==='complete'?Promise.resolve():new Promise(resolve=>{const f=()=>{if(pc.iceGatheringState==='complete'){pc.removeEventListener('icegatheringstatechange',f);resolve();}};pc.addEventListener('icegatheringstatechange',f);setTimeout(resolve,3000);});}"
                    + "async function rtcStream(c){"
                    + " log('creating local RTCPeerConnection');"
                    + " const pc=new RTCPeerConnection({iceServers:[]});"
                    + " const remote=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('WebRTC track timeout')),10000);pc.ontrack=e=>{clearTimeout(timer);resolve(e.track);};});"
                    + " pc.addTransceiver('video',{direction:'recvonly'});"
                    + " await pc.setLocalDescription(await pc.createOffer());await waitIce(pc);log('offer ready length='+pc.localDescription.sdp.length);"
                    + " const answer=window.CamExchBridge&&window.CamExchBridge.answerOffer(pc.localDescription.sdp);if(!answer||answer.indexOf('ERROR:')===0)throw new Error(answer||'Source bridge unavailable');"
                    + " log('answer received length='+answer.length);await pc.setRemoteDescription({type:'answer',sdp:answer});"
                    + " const track=await remote;log('remote track received state='+track.readyState);const stream=new MediaStream([track]);"
                    + " const stop=track.stop.bind(track);track.stop=function(){stop();pc.close();};"
                    + " await addAudio(stream,c);return stream;"
                    + "}"
                    + "async function virtualStream(c){"
                    + " try{const mode=window.CamExchBridge&&window.CamExchBridge.getMode();if(!mode||mode.indexOf('ERROR:')===0)throw new Error(mode||'Source bridge unavailable');log('IPC bridge mode='+mode.trim());if(mode.trim()==='Photo')return photoStream(c);return await rtcStream(c);}catch(e){log('Front Camera 4 unavailable, using phone camera: '+e);return originalGet(c);}"
                    + "}"
                    + "async function routeGet(c){"
                    + " log('getUserMedia '+JSON.stringify(c));"
                    + " if(isVirtualRequest(c))return virtualStream(c);"
                    + " const stream=await originalGet(c);const v=c&&c.video;"
                    + " if(v&&v!==true&&v.deviceId&&!v.facingMode){const track=stream.getVideoTracks()[0];const facing=track&&track.getSettings?track.getSettings().facingMode:'';if(facing==='user'){stream.getTracks().forEach(t=>t.stop());return virtualStream(c);}}"
                    + " return stream;"
                    + "}"
                    + "if(navigator.mediaDevices&&originalGet){navigator.mediaDevices.getUserMedia=routeGet;}"
                    + "if(navigator.mediaDevices&&originalEnum){navigator.mediaDevices.enumerateDevices=async function(){"
                    + " const list=await originalEnum();"
                    + " const virtual={deviceId:'camexch-front-camera-4',kind:'videoinput',label:'Front Camera 4',groupId:'camexch'};"
                    + " return [virtual].concat(list);"
                    + "};}"
                    + "})();";

    private VirtualCameraScript() {
    }
}
